# Generated by Django 4.2.9 on 2024-05-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_menu_id_item_menu'),
        ('employee', '0002_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('menu', 'employee')},
        ),
    ]
